id: AA113A919
base_file: f8989.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:02:26.472324
  last_modified_at: 2022-06-17 14:02:26.472334
