id: AA113A919
base_file: f5AF2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:02:26.462721
  last_modified_at: 2022-06-17 14:02:26.462729
