id: AA113A919
base_file: f2A23.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:02:26.455852
  last_modified_at: 2022-06-17 14:02:26.455865
